name: bottle_crush
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dart_jsonwebtoken: ^2.4.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.1
  flutter_secure_storage: ^9.2.2
  mime: ^1.0.0
  file_picker: ^8.1.6
  excel: ^2.0.5
  path_provider: ^2.0.11
  open_file: ^3.2.1
  permission_handler: ^10.2.0
  intl: ^0.18.0
  url_launcher: ^6.1.7


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4




  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/aquazen_logo.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/leaf.png
    - assets/images/aquazen_logo.png
    - assets/images/aquazen.png



  fonts:
      - family: Merriweather
        fonts:
          - asset: assets/fonts/Merriweather-Regular.ttf
          - asset: assets/fonts/Merriweather-Black.ttf
            weight: 900
          - asset: assets/fonts/Merriweather-BlackItalic.ttf
            weight: 900
            style: italic
          - asset: assets/fonts/Merriweather-Bold.ttf
            weight: 700
          - asset: assets/fonts/Merriweather-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/Merriweather-Italic.ttf
            style: italic
          - asset: assets/fonts/Merriweather-Light.ttf
            weight: 300
          - asset: assets/fonts/Merriweather-LightItalic.ttf
            weight: 300
            style: italic
