name: bottle_crush
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  http: ^1.2.2
  dart_jsonwebtoken: ^2.4.1



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^4.0.0

#flutter_native_splash:
#  color: "#0B499D" # Background color
#  image: assets/images/bottle_logo.png # Path to your logo image
#  android: true # Enable Android splash screen
#  ios: false # Enable iOS splash screen
#  web: false


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/leaf.png
    - assets/json/user_credentials.json
    - assets/json/admin_details.json


  fonts:
      - family: Merriweather
        fonts:
          - asset: assets/fonts/Merriweather-Regular.ttf
          - asset: assets/fonts/Merriweather-Black.ttf
            weight: 900
          - asset: assets/fonts/Merriweather-BlackItalic.ttf
            weight: 900
            style: italic
          - asset: assets/fonts/Merriweather-Bold.ttf
            weight: 700
          - asset: assets/fonts/Merriweather-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/Merriweather-Italic.ttf
            style: italic
          - asset: assets/fonts/Merriweather-Light.ttf
            weight: 300
          - asset: assets/fonts/Merriweather-LightItalic.ttf
            weight: 300
            style: italic
